### ISSUE TITLE
Generate sharable URLs

### ISSUE THREAD

**Issue by domenic** [annevk/live-url-viewer#2]
It seems like the code has some leftovers meant to support this (by reading location.search?) but it doesn't work in general. When you update something the browser's URL bar does not change.

**Comment by annevk** [comment]
The fragment does not change in your browser? It should work for liveview and liveview2 at least. Not sure about the query-related code, haven't looked into that yet.

**Comment by domenic** [comment]
Ah, I guess I must have been testing liveview3.html. Maybe close this if you want to roll it into #1.

**Comment by annevk** [comment]
Yeah, if we do #1 somehow this would automatically come up.
